version: '3.2'

services:
  app:
    image: alksglk/blackjack
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
      image: postgres:14
      restart: always
      environment:
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASS}
          - POSTGRES_DB=${DB_DATABASE}
      ports:
          - 5432:5432
      env_file:
      - .env
      volumes:
      - ./postgres-data:/var/lib/postgresql/data
