"""Stats game

Revision ID: 18db1d6a037b
Revises: dd200e498b0d
Create Date: 2022-09-18 13:51:41.549112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18db1d6a037b'
down_revision = 'dd200e498b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_stats', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('game_stats_game_id_fkey', 'game_stats', type_='foreignkey')
    op.create_foreign_key(None, 'game_stats', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_stats', type_='foreignkey')
    op.create_foreign_key('game_stats_game_id_fkey', 'game_stats', 'game', ['game_id'], ['id'])
    op.alter_column('game_stats', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
