"""PK for player

Revision ID: b0b00301364a
Revises: 26cc36c5e461
Create Date: 2022-09-18 18:39:28.709602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b00301364a'
down_revision = '26cc36c5e461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('us_ga_id', 'player', ['user_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('us_ga_id', 'player', type_='unique')
    # ### end Alembic commands ###
